/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.newoamydsl.myDslnew.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.newoamydsl.myDslnew.AbstractPropertyValue;
import org.xtext.example.newoamydsl.myDslnew.CommunicationMean;
import org.xtext.example.newoamydsl.myDslnew.ComponentExchangeEnd;
import org.xtext.example.newoamydsl.myDslnew.ComponentExchangeFunctionalExchangeAllocation;
import org.xtext.example.newoamydsl.myDslnew.ComponentExchangeKind;
import org.xtext.example.newoamydsl.myDslnew.ComponentExchangeRealization;
import org.xtext.example.newoamydsl.myDslnew.EnumerationPropertyType;
import org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage;
import org.xtext.example.newoamydsl.myDslnew.PropertyValueGroup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Communication Mean</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getSid <em>Sid</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getVisibleInDoc <em>Visible In Doc</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getVisibleInLM <em>Visible In LM</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getSummary <em>Summary</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getKind <em>Kind</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getRealizedFlow <em>Realized Flow</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getAppliedPropertyValues <em>Applied Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getRealizations <em>Realizations</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getConvoyedInformations <em>Convoyed Informations</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOriented <em>Oriented</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedPropertyValues <em>Owned Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedEnumerationPropertyTypes <em>Owned Enumeration Property Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedPropertyValueGroups <em>Owned Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedComponentExchangeFunctionalExchangeAllocations <em>Owned Component Exchange Functional Exchange Allocations</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedComponentExchangeRealizations <em>Owned Component Exchange Realizations</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.CommunicationMeanImpl#getOwnedComponentExchangeEnds <em>Owned Component Exchange Ends</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CommunicationMeanImpl extends MinimalEObjectImpl.Container implements CommunicationMean
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getSid() <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSid()
   * @generated
   * @ordered
   */
  protected static final String SID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSid() <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSid()
   * @generated
   * @ordered
   */
  protected String sid = SID_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibleInDoc() <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInDoc()
   * @generated
   * @ordered
   */
  protected static final String VISIBLE_IN_DOC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVisibleInDoc() <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInDoc()
   * @generated
   * @ordered
   */
  protected String visibleInDoc = VISIBLE_IN_DOC_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibleInLM() <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInLM()
   * @generated
   * @ordered
   */
  protected static final String VISIBLE_IN_LM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVisibleInLM() <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInLM()
   * @generated
   * @ordered
   */
  protected String visibleInLM = VISIBLE_IN_LM_EDEFAULT;

  /**
   * The default value of the '{@link #getSummary() <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSummary()
   * @generated
   * @ordered
   */
  protected static final String SUMMARY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSummary() <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSummary()
   * @generated
   * @ordered
   */
  protected String summary = SUMMARY_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getReview() <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReview()
   * @generated
   * @ordered
   */
  protected static final String REVIEW_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReview() <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReview()
   * @generated
   * @ordered
   */
  protected String review = REVIEW_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected static final ComponentExchangeKind KIND_EDEFAULT = ComponentExchangeKind.UNSET;

  /**
   * The cached value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected ComponentExchangeKind kind = KIND_EDEFAULT;

  /**
   * The default value of the '{@link #getRealizedFlow() <em>Realized Flow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRealizedFlow()
   * @generated
   * @ordered
   */
  protected static final String REALIZED_FLOW_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRealizedFlow() <em>Realized Flow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRealizedFlow()
   * @generated
   * @ordered
   */
  protected String realizedFlow = REALIZED_FLOW_EDEFAULT;

  /**
   * The default value of the '{@link #getAppliedPropertyValues() <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValues()
   * @generated
   * @ordered
   */
  protected static final String APPLIED_PROPERTY_VALUES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAppliedPropertyValues() <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValues()
   * @generated
   * @ordered
   */
  protected String appliedPropertyValues = APPLIED_PROPERTY_VALUES_EDEFAULT;

  /**
   * The default value of the '{@link #getAppliedPropertyValueGroups() <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected static final String APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAppliedPropertyValueGroups() <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected String appliedPropertyValueGroups = APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT;

  /**
   * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected static final String STATUS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected String status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #getFeatures() <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected static final String FEATURES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFeatures() <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected String features = FEATURES_EDEFAULT;

  /**
   * The default value of the '{@link #getRealizations() <em>Realizations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRealizations()
   * @generated
   * @ordered
   */
  protected static final String REALIZATIONS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRealizations() <em>Realizations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRealizations()
   * @generated
   * @ordered
   */
  protected String realizations = REALIZATIONS_EDEFAULT;

  /**
   * The default value of the '{@link #getConvoyedInformations() <em>Convoyed Informations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvoyedInformations()
   * @generated
   * @ordered
   */
  protected static final String CONVOYED_INFORMATIONS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConvoyedInformations() <em>Convoyed Informations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvoyedInformations()
   * @generated
   * @ordered
   */
  protected String convoyedInformations = CONVOYED_INFORMATIONS_EDEFAULT;

  /**
   * The default value of the '{@link #getSource() <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected static final String SOURCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSource() <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected String source = SOURCE_EDEFAULT;

  /**
   * The default value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected static final String TARGET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected String target = TARGET_EDEFAULT;

  /**
   * The default value of the '{@link #getLink() <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLink()
   * @generated
   * @ordered
   */
  protected static final String LINK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLink() <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLink()
   * @generated
   * @ordered
   */
  protected String link = LINK_EDEFAULT;

  /**
   * The default value of the '{@link #getOriented() <em>Oriented</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriented()
   * @generated
   * @ordered
   */
  protected static final String ORIENTED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOriented() <em>Oriented</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriented()
   * @generated
   * @ordered
   */
  protected String oriented = ORIENTED_EDEFAULT;

  /**
   * The cached value of the '{@link #getOwnedPropertyValues() <em>Owned Property Values</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPropertyValues()
   * @generated
   * @ordered
   */
  protected EList<AbstractPropertyValue> ownedPropertyValues;

  /**
   * The cached value of the '{@link #getOwnedEnumerationPropertyTypes() <em>Owned Enumeration Property Types</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedEnumerationPropertyTypes()
   * @generated
   * @ordered
   */
  protected EList<EnumerationPropertyType> ownedEnumerationPropertyTypes;

  /**
   * The cached value of the '{@link #getOwnedPropertyValueGroups() <em>Owned Property Value Groups</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected EList<PropertyValueGroup> ownedPropertyValueGroups;

  /**
   * The cached value of the '{@link #getOwnedComponentExchangeFunctionalExchangeAllocations() <em>Owned Component Exchange Functional Exchange Allocations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedComponentExchangeFunctionalExchangeAllocations()
   * @generated
   * @ordered
   */
  protected EList<ComponentExchangeFunctionalExchangeAllocation> ownedComponentExchangeFunctionalExchangeAllocations;

  /**
   * The cached value of the '{@link #getOwnedComponentExchangeRealizations() <em>Owned Component Exchange Realizations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedComponentExchangeRealizations()
   * @generated
   * @ordered
   */
  protected EList<ComponentExchangeRealization> ownedComponentExchangeRealizations;

  /**
   * The cached value of the '{@link #getOwnedComponentExchangeEnds() <em>Owned Component Exchange Ends</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedComponentExchangeEnds()
   * @generated
   * @ordered
   */
  protected EList<ComponentExchangeEnd> ownedComponentExchangeEnds;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommunicationMeanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslnewPackage.eINSTANCE.getCommunicationMean();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSid()
  {
    return sid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSid(String newSid)
  {
    String oldSid = sid;
    sid = newSid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__SID, oldSid, sid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVisibleInDoc()
  {
    return visibleInDoc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibleInDoc(String newVisibleInDoc)
  {
    String oldVisibleInDoc = visibleInDoc;
    visibleInDoc = newVisibleInDoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_DOC, oldVisibleInDoc, visibleInDoc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVisibleInLM()
  {
    return visibleInLM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibleInLM(String newVisibleInLM)
  {
    String oldVisibleInLM = visibleInLM;
    visibleInLM = newVisibleInLM;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_LM, oldVisibleInLM, visibleInLM));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSummary()
  {
    return summary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSummary(String newSummary)
  {
    String oldSummary = summary;
    summary = newSummary;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__SUMMARY, oldSummary, summary));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getReview()
  {
    return review;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReview(String newReview)
  {
    String oldReview = review;
    review = newReview;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__REVIEW, oldReview, review));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComponentExchangeKind getKind()
  {
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKind(ComponentExchangeKind newKind)
  {
    ComponentExchangeKind oldKind = kind;
    kind = newKind == null ? KIND_EDEFAULT : newKind;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__KIND, oldKind, kind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRealizedFlow()
  {
    return realizedFlow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRealizedFlow(String newRealizedFlow)
  {
    String oldRealizedFlow = realizedFlow;
    realizedFlow = newRealizedFlow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__REALIZED_FLOW, oldRealizedFlow, realizedFlow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAppliedPropertyValues()
  {
    return appliedPropertyValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAppliedPropertyValues(String newAppliedPropertyValues)
  {
    String oldAppliedPropertyValues = appliedPropertyValues;
    appliedPropertyValues = newAppliedPropertyValues;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUES, oldAppliedPropertyValues, appliedPropertyValues));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAppliedPropertyValueGroups()
  {
    return appliedPropertyValueGroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAppliedPropertyValueGroups(String newAppliedPropertyValueGroups)
  {
    String oldAppliedPropertyValueGroups = appliedPropertyValueGroups;
    appliedPropertyValueGroups = newAppliedPropertyValueGroups;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUE_GROUPS, oldAppliedPropertyValueGroups, appliedPropertyValueGroups));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(String newStatus)
  {
    String oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFeatures()
  {
    return features;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFeatures(String newFeatures)
  {
    String oldFeatures = features;
    features = newFeatures;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__FEATURES, oldFeatures, features));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRealizations()
  {
    return realizations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRealizations(String newRealizations)
  {
    String oldRealizations = realizations;
    realizations = newRealizations;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__REALIZATIONS, oldRealizations, realizations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConvoyedInformations()
  {
    return convoyedInformations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConvoyedInformations(String newConvoyedInformations)
  {
    String oldConvoyedInformations = convoyedInformations;
    convoyedInformations = newConvoyedInformations;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__CONVOYED_INFORMATIONS, oldConvoyedInformations, convoyedInformations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSource()
  {
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSource(String newSource)
  {
    String oldSource = source;
    source = newSource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__SOURCE, oldSource, source));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTarget(String newTarget)
  {
    String oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__TARGET, oldTarget, target));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLink()
  {
    return link;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLink(String newLink)
  {
    String oldLink = link;
    link = newLink;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__LINK, oldLink, link));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOriented()
  {
    return oriented;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOriented(String newOriented)
  {
    String oldOriented = oriented;
    oriented = newOriented;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.COMMUNICATION_MEAN__ORIENTED, oldOriented, oriented));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AbstractPropertyValue> getOwnedPropertyValues()
  {
    if (ownedPropertyValues == null)
    {
      ownedPropertyValues = new EObjectContainmentEList<AbstractPropertyValue>(AbstractPropertyValue.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES);
    }
    return ownedPropertyValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumerationPropertyType> getOwnedEnumerationPropertyTypes()
  {
    if (ownedEnumerationPropertyTypes == null)
    {
      ownedEnumerationPropertyTypes = new EObjectContainmentEList<EnumerationPropertyType>(EnumerationPropertyType.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES);
    }
    return ownedEnumerationPropertyTypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PropertyValueGroup> getOwnedPropertyValueGroups()
  {
    if (ownedPropertyValueGroups == null)
    {
      ownedPropertyValueGroups = new EObjectContainmentEList<PropertyValueGroup>(PropertyValueGroup.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS);
    }
    return ownedPropertyValueGroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ComponentExchangeFunctionalExchangeAllocation> getOwnedComponentExchangeFunctionalExchangeAllocations()
  {
    if (ownedComponentExchangeFunctionalExchangeAllocations == null)
    {
      ownedComponentExchangeFunctionalExchangeAllocations = new EObjectContainmentEList<ComponentExchangeFunctionalExchangeAllocation>(ComponentExchangeFunctionalExchangeAllocation.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS);
    }
    return ownedComponentExchangeFunctionalExchangeAllocations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ComponentExchangeRealization> getOwnedComponentExchangeRealizations()
  {
    if (ownedComponentExchangeRealizations == null)
    {
      ownedComponentExchangeRealizations = new EObjectContainmentEList<ComponentExchangeRealization>(ComponentExchangeRealization.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS);
    }
    return ownedComponentExchangeRealizations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ComponentExchangeEnd> getOwnedComponentExchangeEnds()
  {
    if (ownedComponentExchangeEnds == null)
    {
      ownedComponentExchangeEnds = new EObjectContainmentEList<ComponentExchangeEnd>(ComponentExchangeEnd.class, this, MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS);
    }
    return ownedComponentExchangeEnds;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES:
        return ((InternalEList<?>)getOwnedPropertyValues()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES:
        return ((InternalEList<?>)getOwnedEnumerationPropertyTypes()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS:
        return ((InternalEList<?>)getOwnedPropertyValueGroups()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS:
        return ((InternalEList<?>)getOwnedComponentExchangeFunctionalExchangeAllocations()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS:
        return ((InternalEList<?>)getOwnedComponentExchangeRealizations()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS:
        return ((InternalEList<?>)getOwnedComponentExchangeEnds()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslnewPackage.COMMUNICATION_MEAN__TYPE:
        return getType();
      case MyDslnewPackage.COMMUNICATION_MEAN__ID:
        return getId();
      case MyDslnewPackage.COMMUNICATION_MEAN__SID:
        return getSid();
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_DOC:
        return getVisibleInDoc();
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_LM:
        return getVisibleInLM();
      case MyDslnewPackage.COMMUNICATION_MEAN__SUMMARY:
        return getSummary();
      case MyDslnewPackage.COMMUNICATION_MEAN__DESCRIPTION:
        return getDescription();
      case MyDslnewPackage.COMMUNICATION_MEAN__REVIEW:
        return getReview();
      case MyDslnewPackage.COMMUNICATION_MEAN__NAME:
        return getName();
      case MyDslnewPackage.COMMUNICATION_MEAN__KIND:
        return getKind();
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZED_FLOW:
        return getRealizedFlow();
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUES:
        return getAppliedPropertyValues();
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUE_GROUPS:
        return getAppliedPropertyValueGroups();
      case MyDslnewPackage.COMMUNICATION_MEAN__STATUS:
        return getStatus();
      case MyDslnewPackage.COMMUNICATION_MEAN__FEATURES:
        return getFeatures();
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZATIONS:
        return getRealizations();
      case MyDslnewPackage.COMMUNICATION_MEAN__CONVOYED_INFORMATIONS:
        return getConvoyedInformations();
      case MyDslnewPackage.COMMUNICATION_MEAN__SOURCE:
        return getSource();
      case MyDslnewPackage.COMMUNICATION_MEAN__TARGET:
        return getTarget();
      case MyDslnewPackage.COMMUNICATION_MEAN__LINK:
        return getLink();
      case MyDslnewPackage.COMMUNICATION_MEAN__ORIENTED:
        return getOriented();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES:
        return getOwnedPropertyValues();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES:
        return getOwnedEnumerationPropertyTypes();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS:
        return getOwnedPropertyValueGroups();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS:
        return getOwnedComponentExchangeFunctionalExchangeAllocations();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS:
        return getOwnedComponentExchangeRealizations();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS:
        return getOwnedComponentExchangeEnds();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslnewPackage.COMMUNICATION_MEAN__TYPE:
        setType((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__ID:
        setId((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SID:
        setSid((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_DOC:
        setVisibleInDoc((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_LM:
        setVisibleInLM((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SUMMARY:
        setSummary((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REVIEW:
        setReview((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__NAME:
        setName((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__KIND:
        setKind((ComponentExchangeKind)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZED_FLOW:
        setRealizedFlow((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUES:
        setAppliedPropertyValues((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUE_GROUPS:
        setAppliedPropertyValueGroups((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__STATUS:
        setStatus((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__FEATURES:
        setFeatures((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZATIONS:
        setRealizations((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__CONVOYED_INFORMATIONS:
        setConvoyedInformations((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SOURCE:
        setSource((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__TARGET:
        setTarget((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__LINK:
        setLink((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__ORIENTED:
        setOriented((String)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES:
        getOwnedPropertyValues().clear();
        getOwnedPropertyValues().addAll((Collection<? extends AbstractPropertyValue>)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES:
        getOwnedEnumerationPropertyTypes().clear();
        getOwnedEnumerationPropertyTypes().addAll((Collection<? extends EnumerationPropertyType>)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS:
        getOwnedPropertyValueGroups().clear();
        getOwnedPropertyValueGroups().addAll((Collection<? extends PropertyValueGroup>)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS:
        getOwnedComponentExchangeFunctionalExchangeAllocations().clear();
        getOwnedComponentExchangeFunctionalExchangeAllocations().addAll((Collection<? extends ComponentExchangeFunctionalExchangeAllocation>)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS:
        getOwnedComponentExchangeRealizations().clear();
        getOwnedComponentExchangeRealizations().addAll((Collection<? extends ComponentExchangeRealization>)newValue);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS:
        getOwnedComponentExchangeEnds().clear();
        getOwnedComponentExchangeEnds().addAll((Collection<? extends ComponentExchangeEnd>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslnewPackage.COMMUNICATION_MEAN__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__ID:
        setId(ID_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SID:
        setSid(SID_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_DOC:
        setVisibleInDoc(VISIBLE_IN_DOC_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_LM:
        setVisibleInLM(VISIBLE_IN_LM_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SUMMARY:
        setSummary(SUMMARY_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REVIEW:
        setReview(REVIEW_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__KIND:
        setKind(KIND_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZED_FLOW:
        setRealizedFlow(REALIZED_FLOW_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUES:
        setAppliedPropertyValues(APPLIED_PROPERTY_VALUES_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUE_GROUPS:
        setAppliedPropertyValueGroups(APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__FEATURES:
        setFeatures(FEATURES_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZATIONS:
        setRealizations(REALIZATIONS_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__CONVOYED_INFORMATIONS:
        setConvoyedInformations(CONVOYED_INFORMATIONS_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__SOURCE:
        setSource(SOURCE_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__TARGET:
        setTarget(TARGET_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__LINK:
        setLink(LINK_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__ORIENTED:
        setOriented(ORIENTED_EDEFAULT);
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES:
        getOwnedPropertyValues().clear();
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES:
        getOwnedEnumerationPropertyTypes().clear();
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS:
        getOwnedPropertyValueGroups().clear();
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS:
        getOwnedComponentExchangeFunctionalExchangeAllocations().clear();
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS:
        getOwnedComponentExchangeRealizations().clear();
        return;
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS:
        getOwnedComponentExchangeEnds().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslnewPackage.COMMUNICATION_MEAN__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case MyDslnewPackage.COMMUNICATION_MEAN__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case MyDslnewPackage.COMMUNICATION_MEAN__SID:
        return SID_EDEFAULT == null ? sid != null : !SID_EDEFAULT.equals(sid);
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_DOC:
        return VISIBLE_IN_DOC_EDEFAULT == null ? visibleInDoc != null : !VISIBLE_IN_DOC_EDEFAULT.equals(visibleInDoc);
      case MyDslnewPackage.COMMUNICATION_MEAN__VISIBLE_IN_LM:
        return VISIBLE_IN_LM_EDEFAULT == null ? visibleInLM != null : !VISIBLE_IN_LM_EDEFAULT.equals(visibleInLM);
      case MyDslnewPackage.COMMUNICATION_MEAN__SUMMARY:
        return SUMMARY_EDEFAULT == null ? summary != null : !SUMMARY_EDEFAULT.equals(summary);
      case MyDslnewPackage.COMMUNICATION_MEAN__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MyDslnewPackage.COMMUNICATION_MEAN__REVIEW:
        return REVIEW_EDEFAULT == null ? review != null : !REVIEW_EDEFAULT.equals(review);
      case MyDslnewPackage.COMMUNICATION_MEAN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslnewPackage.COMMUNICATION_MEAN__KIND:
        return kind != KIND_EDEFAULT;
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZED_FLOW:
        return REALIZED_FLOW_EDEFAULT == null ? realizedFlow != null : !REALIZED_FLOW_EDEFAULT.equals(realizedFlow);
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUES:
        return APPLIED_PROPERTY_VALUES_EDEFAULT == null ? appliedPropertyValues != null : !APPLIED_PROPERTY_VALUES_EDEFAULT.equals(appliedPropertyValues);
      case MyDslnewPackage.COMMUNICATION_MEAN__APPLIED_PROPERTY_VALUE_GROUPS:
        return APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT == null ? appliedPropertyValueGroups != null : !APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT.equals(appliedPropertyValueGroups);
      case MyDslnewPackage.COMMUNICATION_MEAN__STATUS:
        return STATUS_EDEFAULT == null ? status != null : !STATUS_EDEFAULT.equals(status);
      case MyDslnewPackage.COMMUNICATION_MEAN__FEATURES:
        return FEATURES_EDEFAULT == null ? features != null : !FEATURES_EDEFAULT.equals(features);
      case MyDslnewPackage.COMMUNICATION_MEAN__REALIZATIONS:
        return REALIZATIONS_EDEFAULT == null ? realizations != null : !REALIZATIONS_EDEFAULT.equals(realizations);
      case MyDslnewPackage.COMMUNICATION_MEAN__CONVOYED_INFORMATIONS:
        return CONVOYED_INFORMATIONS_EDEFAULT == null ? convoyedInformations != null : !CONVOYED_INFORMATIONS_EDEFAULT.equals(convoyedInformations);
      case MyDslnewPackage.COMMUNICATION_MEAN__SOURCE:
        return SOURCE_EDEFAULT == null ? source != null : !SOURCE_EDEFAULT.equals(source);
      case MyDslnewPackage.COMMUNICATION_MEAN__TARGET:
        return TARGET_EDEFAULT == null ? target != null : !TARGET_EDEFAULT.equals(target);
      case MyDslnewPackage.COMMUNICATION_MEAN__LINK:
        return LINK_EDEFAULT == null ? link != null : !LINK_EDEFAULT.equals(link);
      case MyDslnewPackage.COMMUNICATION_MEAN__ORIENTED:
        return ORIENTED_EDEFAULT == null ? oriented != null : !ORIENTED_EDEFAULT.equals(oriented);
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUES:
        return ownedPropertyValues != null && !ownedPropertyValues.isEmpty();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_ENUMERATION_PROPERTY_TYPES:
        return ownedEnumerationPropertyTypes != null && !ownedEnumerationPropertyTypes.isEmpty();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_PROPERTY_VALUE_GROUPS:
        return ownedPropertyValueGroups != null && !ownedPropertyValueGroups.isEmpty();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_FUNCTIONAL_EXCHANGE_ALLOCATIONS:
        return ownedComponentExchangeFunctionalExchangeAllocations != null && !ownedComponentExchangeFunctionalExchangeAllocations.isEmpty();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_REALIZATIONS:
        return ownedComponentExchangeRealizations != null && !ownedComponentExchangeRealizations.isEmpty();
      case MyDslnewPackage.COMMUNICATION_MEAN__OWNED_COMPONENT_EXCHANGE_ENDS:
        return ownedComponentExchangeEnds != null && !ownedComponentExchangeEnds.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", id: ");
    result.append(id);
    result.append(", sid: ");
    result.append(sid);
    result.append(", visibleInDoc: ");
    result.append(visibleInDoc);
    result.append(", visibleInLM: ");
    result.append(visibleInLM);
    result.append(", summary: ");
    result.append(summary);
    result.append(", description: ");
    result.append(description);
    result.append(", review: ");
    result.append(review);
    result.append(", name: ");
    result.append(name);
    result.append(", kind: ");
    result.append(kind);
    result.append(", realizedFlow: ");
    result.append(realizedFlow);
    result.append(", appliedPropertyValues: ");
    result.append(appliedPropertyValues);
    result.append(", appliedPropertyValueGroups: ");
    result.append(appliedPropertyValueGroups);
    result.append(", status: ");
    result.append(status);
    result.append(", features: ");
    result.append(features);
    result.append(", realizations: ");
    result.append(realizations);
    result.append(", convoyedInformations: ");
    result.append(convoyedInformations);
    result.append(", source: ");
    result.append(source);
    result.append(", target: ");
    result.append(target);
    result.append(", link: ");
    result.append(link);
    result.append(", oriented: ");
    result.append(oriented);
    result.append(')');
    return result.toString();
  }

} //CommunicationMeanImpl
