/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.newoamydsl.myDslnew.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.newoamydsl.myDslnew.AbstractPropertyValue;
import org.xtext.example.newoamydsl.myDslnew.Association;
import org.xtext.example.newoamydsl.myDslnew.Collection;
import org.xtext.example.newoamydsl.myDslnew.DataPkg;
import org.xtext.example.newoamydsl.myDslnew.DataType;
import org.xtext.example.newoamydsl.myDslnew.DataValue;
import org.xtext.example.newoamydsl.myDslnew.EnumerationPropertyType;
import org.xtext.example.newoamydsl.myDslnew.ExchangeItem;
import org.xtext.example.newoamydsl.myDslnew.KeyPart;
import org.xtext.example.newoamydsl.myDslnew.Message;
import org.xtext.example.newoamydsl.myDslnew.MessageReference;
import org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage;
import org.xtext.example.newoamydsl.myDslnew.PropertyValueGroup;
import org.xtext.example.newoamydsl.myDslnew.PropertyValuePkg;
import org.xtext.example.newoamydsl.myDslnew.Signal;
import org.xtext.example.newoamydsl.myDslnew.StateEvent;
import org.xtext.example.newoamydsl.myDslnew.Trace;
import org.xtext.example.newoamydsl.myDslnew.Unit;
import org.xtext.example.newoamydsl.myDslnew.VisibilityKind;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Pkg</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getSid <em>Sid</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getVisibleInDoc <em>Visible In Doc</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getVisibleInLM <em>Visible In LM</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getSummary <em>Summary</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getAppliedPropertyValues <em>Applied Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedPropertyValues <em>Owned Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedEnumerationPropertyTypes <em>Owned Enumeration Property Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedPropertyValueGroups <em>Owned Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedTraces <em>Owned Traces</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedPropertyValuePkgs <em>Owned Property Value Pkgs</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedExchangeItems <em>Owned Exchange Items</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedAssociations <em>Owned Associations</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedDataValues <em>Owned Data Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedMessageReferences <em>Owned Message References</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedDataPkgs <em>Owned Data Pkgs</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedClasses <em>Owned Classes</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedKeyParts <em>Owned Key Parts</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedCollections <em>Owned Collections</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedUnits <em>Owned Units</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedDataTypes <em>Owned Data Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedSignals <em>Owned Signals</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedMessages <em>Owned Messages</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedExceptions <em>Owned Exceptions</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.impl.DataPkgImpl#getOwnedStateEvents <em>Owned State Events</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataPkgImpl extends MinimalEObjectImpl.Container implements DataPkg
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getSid() <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSid()
   * @generated
   * @ordered
   */
  protected static final String SID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSid() <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSid()
   * @generated
   * @ordered
   */
  protected String sid = SID_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibleInDoc() <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInDoc()
   * @generated
   * @ordered
   */
  protected static final String VISIBLE_IN_DOC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVisibleInDoc() <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInDoc()
   * @generated
   * @ordered
   */
  protected String visibleInDoc = VISIBLE_IN_DOC_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibleInLM() <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInLM()
   * @generated
   * @ordered
   */
  protected static final String VISIBLE_IN_LM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVisibleInLM() <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleInLM()
   * @generated
   * @ordered
   */
  protected String visibleInLM = VISIBLE_IN_LM_EDEFAULT;

  /**
   * The default value of the '{@link #getSummary() <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSummary()
   * @generated
   * @ordered
   */
  protected static final String SUMMARY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSummary() <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSummary()
   * @generated
   * @ordered
   */
  protected String summary = SUMMARY_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getReview() <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReview()
   * @generated
   * @ordered
   */
  protected static final String REVIEW_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReview() <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReview()
   * @generated
   * @ordered
   */
  protected String review = REVIEW_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected static final VisibilityKind VISIBILITY_EDEFAULT = VisibilityKind.UNSET;

  /**
   * The cached value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected VisibilityKind visibility = VISIBILITY_EDEFAULT;

  /**
   * The default value of the '{@link #getAppliedPropertyValues() <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValues()
   * @generated
   * @ordered
   */
  protected static final String APPLIED_PROPERTY_VALUES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAppliedPropertyValues() <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValues()
   * @generated
   * @ordered
   */
  protected String appliedPropertyValues = APPLIED_PROPERTY_VALUES_EDEFAULT;

  /**
   * The default value of the '{@link #getAppliedPropertyValueGroups() <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected static final String APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAppliedPropertyValueGroups() <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected String appliedPropertyValueGroups = APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT;

  /**
   * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected static final String STATUS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected String status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #getFeatures() <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected static final String FEATURES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFeatures() <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected String features = FEATURES_EDEFAULT;

  /**
   * The cached value of the '{@link #getOwnedPropertyValues() <em>Owned Property Values</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPropertyValues()
   * @generated
   * @ordered
   */
  protected EList<AbstractPropertyValue> ownedPropertyValues;

  /**
   * The cached value of the '{@link #getOwnedEnumerationPropertyTypes() <em>Owned Enumeration Property Types</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedEnumerationPropertyTypes()
   * @generated
   * @ordered
   */
  protected EList<EnumerationPropertyType> ownedEnumerationPropertyTypes;

  /**
   * The cached value of the '{@link #getOwnedPropertyValueGroups() <em>Owned Property Value Groups</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPropertyValueGroups()
   * @generated
   * @ordered
   */
  protected EList<PropertyValueGroup> ownedPropertyValueGroups;

  /**
   * The cached value of the '{@link #getOwnedTraces() <em>Owned Traces</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedTraces()
   * @generated
   * @ordered
   */
  protected EList<Trace> ownedTraces;

  /**
   * The cached value of the '{@link #getOwnedPropertyValuePkgs() <em>Owned Property Value Pkgs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedPropertyValuePkgs()
   * @generated
   * @ordered
   */
  protected EList<PropertyValuePkg> ownedPropertyValuePkgs;

  /**
   * The cached value of the '{@link #getOwnedExchangeItems() <em>Owned Exchange Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedExchangeItems()
   * @generated
   * @ordered
   */
  protected EList<ExchangeItem> ownedExchangeItems;

  /**
   * The cached value of the '{@link #getOwnedAssociations() <em>Owned Associations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedAssociations()
   * @generated
   * @ordered
   */
  protected EList<Association> ownedAssociations;

  /**
   * The cached value of the '{@link #getOwnedDataValues() <em>Owned Data Values</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedDataValues()
   * @generated
   * @ordered
   */
  protected EList<DataValue> ownedDataValues;

  /**
   * The cached value of the '{@link #getOwnedMessageReferences() <em>Owned Message References</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedMessageReferences()
   * @generated
   * @ordered
   */
  protected EList<MessageReference> ownedMessageReferences;

  /**
   * The cached value of the '{@link #getOwnedDataPkgs() <em>Owned Data Pkgs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedDataPkgs()
   * @generated
   * @ordered
   */
  protected EList<DataPkg> ownedDataPkgs;

  /**
   * The cached value of the '{@link #getOwnedClasses() <em>Owned Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedClasses()
   * @generated
   * @ordered
   */
  protected EList<org.xtext.example.newoamydsl.myDslnew.Class> ownedClasses;

  /**
   * The cached value of the '{@link #getOwnedKeyParts() <em>Owned Key Parts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedKeyParts()
   * @generated
   * @ordered
   */
  protected EList<KeyPart> ownedKeyParts;

  /**
   * The cached value of the '{@link #getOwnedCollections() <em>Owned Collections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedCollections()
   * @generated
   * @ordered
   */
  protected EList<Collection> ownedCollections;

  /**
   * The cached value of the '{@link #getOwnedUnits() <em>Owned Units</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedUnits()
   * @generated
   * @ordered
   */
  protected EList<Unit> ownedUnits;

  /**
   * The cached value of the '{@link #getOwnedDataTypes() <em>Owned Data Types</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedDataTypes()
   * @generated
   * @ordered
   */
  protected EList<DataType> ownedDataTypes;

  /**
   * The cached value of the '{@link #getOwnedSignals() <em>Owned Signals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedSignals()
   * @generated
   * @ordered
   */
  protected EList<Signal> ownedSignals;

  /**
   * The cached value of the '{@link #getOwnedMessages() <em>Owned Messages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedMessages()
   * @generated
   * @ordered
   */
  protected EList<Message> ownedMessages;

  /**
   * The cached value of the '{@link #getOwnedExceptions() <em>Owned Exceptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedExceptions()
   * @generated
   * @ordered
   */
  protected EList<org.xtext.example.newoamydsl.myDslnew.Exception> ownedExceptions;

  /**
   * The cached value of the '{@link #getOwnedStateEvents() <em>Owned State Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedStateEvents()
   * @generated
   * @ordered
   */
  protected EList<StateEvent> ownedStateEvents;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataPkgImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslnewPackage.eINSTANCE.getDataPkg();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSid()
  {
    return sid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSid(String newSid)
  {
    String oldSid = sid;
    sid = newSid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__SID, oldSid, sid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVisibleInDoc()
  {
    return visibleInDoc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibleInDoc(String newVisibleInDoc)
  {
    String oldVisibleInDoc = visibleInDoc;
    visibleInDoc = newVisibleInDoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__VISIBLE_IN_DOC, oldVisibleInDoc, visibleInDoc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVisibleInLM()
  {
    return visibleInLM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibleInLM(String newVisibleInLM)
  {
    String oldVisibleInLM = visibleInLM;
    visibleInLM = newVisibleInLM;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__VISIBLE_IN_LM, oldVisibleInLM, visibleInLM));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSummary()
  {
    return summary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSummary(String newSummary)
  {
    String oldSummary = summary;
    summary = newSummary;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__SUMMARY, oldSummary, summary));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getReview()
  {
    return review;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReview(String newReview)
  {
    String oldReview = review;
    review = newReview;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__REVIEW, oldReview, review));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VisibilityKind getVisibility()
  {
    return visibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibility(VisibilityKind newVisibility)
  {
    VisibilityKind oldVisibility = visibility;
    visibility = newVisibility == null ? VISIBILITY_EDEFAULT : newVisibility;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__VISIBILITY, oldVisibility, visibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAppliedPropertyValues()
  {
    return appliedPropertyValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAppliedPropertyValues(String newAppliedPropertyValues)
  {
    String oldAppliedPropertyValues = appliedPropertyValues;
    appliedPropertyValues = newAppliedPropertyValues;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUES, oldAppliedPropertyValues, appliedPropertyValues));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAppliedPropertyValueGroups()
  {
    return appliedPropertyValueGroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAppliedPropertyValueGroups(String newAppliedPropertyValueGroups)
  {
    String oldAppliedPropertyValueGroups = appliedPropertyValueGroups;
    appliedPropertyValueGroups = newAppliedPropertyValueGroups;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUE_GROUPS, oldAppliedPropertyValueGroups, appliedPropertyValueGroups));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(String newStatus)
  {
    String oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFeatures()
  {
    return features;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFeatures(String newFeatures)
  {
    String oldFeatures = features;
    features = newFeatures;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslnewPackage.DATA_PKG__FEATURES, oldFeatures, features));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AbstractPropertyValue> getOwnedPropertyValues()
  {
    if (ownedPropertyValues == null)
    {
      ownedPropertyValues = new EObjectContainmentEList<AbstractPropertyValue>(AbstractPropertyValue.class, this, MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES);
    }
    return ownedPropertyValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumerationPropertyType> getOwnedEnumerationPropertyTypes()
  {
    if (ownedEnumerationPropertyTypes == null)
    {
      ownedEnumerationPropertyTypes = new EObjectContainmentEList<EnumerationPropertyType>(EnumerationPropertyType.class, this, MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES);
    }
    return ownedEnumerationPropertyTypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PropertyValueGroup> getOwnedPropertyValueGroups()
  {
    if (ownedPropertyValueGroups == null)
    {
      ownedPropertyValueGroups = new EObjectContainmentEList<PropertyValueGroup>(PropertyValueGroup.class, this, MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS);
    }
    return ownedPropertyValueGroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Trace> getOwnedTraces()
  {
    if (ownedTraces == null)
    {
      ownedTraces = new EObjectContainmentEList<Trace>(Trace.class, this, MyDslnewPackage.DATA_PKG__OWNED_TRACES);
    }
    return ownedTraces;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PropertyValuePkg> getOwnedPropertyValuePkgs()
  {
    if (ownedPropertyValuePkgs == null)
    {
      ownedPropertyValuePkgs = new EObjectContainmentEList<PropertyValuePkg>(PropertyValuePkg.class, this, MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS);
    }
    return ownedPropertyValuePkgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExchangeItem> getOwnedExchangeItems()
  {
    if (ownedExchangeItems == null)
    {
      ownedExchangeItems = new EObjectContainmentEList<ExchangeItem>(ExchangeItem.class, this, MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS);
    }
    return ownedExchangeItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Association> getOwnedAssociations()
  {
    if (ownedAssociations == null)
    {
      ownedAssociations = new EObjectContainmentEList<Association>(Association.class, this, MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS);
    }
    return ownedAssociations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DataValue> getOwnedDataValues()
  {
    if (ownedDataValues == null)
    {
      ownedDataValues = new EObjectContainmentEList<DataValue>(DataValue.class, this, MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES);
    }
    return ownedDataValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MessageReference> getOwnedMessageReferences()
  {
    if (ownedMessageReferences == null)
    {
      ownedMessageReferences = new EObjectContainmentEList<MessageReference>(MessageReference.class, this, MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES);
    }
    return ownedMessageReferences;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DataPkg> getOwnedDataPkgs()
  {
    if (ownedDataPkgs == null)
    {
      ownedDataPkgs = new EObjectContainmentEList<DataPkg>(DataPkg.class, this, MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS);
    }
    return ownedDataPkgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<org.xtext.example.newoamydsl.myDslnew.Class> getOwnedClasses()
  {
    if (ownedClasses == null)
    {
      ownedClasses = new EObjectContainmentEList<org.xtext.example.newoamydsl.myDslnew.Class>(org.xtext.example.newoamydsl.myDslnew.Class.class, this, MyDslnewPackage.DATA_PKG__OWNED_CLASSES);
    }
    return ownedClasses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<KeyPart> getOwnedKeyParts()
  {
    if (ownedKeyParts == null)
    {
      ownedKeyParts = new EObjectContainmentEList<KeyPart>(KeyPart.class, this, MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS);
    }
    return ownedKeyParts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Collection> getOwnedCollections()
  {
    if (ownedCollections == null)
    {
      ownedCollections = new EObjectContainmentEList<Collection>(Collection.class, this, MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS);
    }
    return ownedCollections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Unit> getOwnedUnits()
  {
    if (ownedUnits == null)
    {
      ownedUnits = new EObjectContainmentEList<Unit>(Unit.class, this, MyDslnewPackage.DATA_PKG__OWNED_UNITS);
    }
    return ownedUnits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DataType> getOwnedDataTypes()
  {
    if (ownedDataTypes == null)
    {
      ownedDataTypes = new EObjectContainmentEList<DataType>(DataType.class, this, MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES);
    }
    return ownedDataTypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Signal> getOwnedSignals()
  {
    if (ownedSignals == null)
    {
      ownedSignals = new EObjectContainmentEList<Signal>(Signal.class, this, MyDslnewPackage.DATA_PKG__OWNED_SIGNALS);
    }
    return ownedSignals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Message> getOwnedMessages()
  {
    if (ownedMessages == null)
    {
      ownedMessages = new EObjectContainmentEList<Message>(Message.class, this, MyDslnewPackage.DATA_PKG__OWNED_MESSAGES);
    }
    return ownedMessages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<org.xtext.example.newoamydsl.myDslnew.Exception> getOwnedExceptions()
  {
    if (ownedExceptions == null)
    {
      ownedExceptions = new EObjectContainmentEList<org.xtext.example.newoamydsl.myDslnew.Exception>(org.xtext.example.newoamydsl.myDslnew.Exception.class, this, MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS);
    }
    return ownedExceptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StateEvent> getOwnedStateEvents()
  {
    if (ownedStateEvents == null)
    {
      ownedStateEvents = new EObjectContainmentEList<StateEvent>(StateEvent.class, this, MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS);
    }
    return ownedStateEvents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES:
        return ((InternalEList<?>)getOwnedPropertyValues()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES:
        return ((InternalEList<?>)getOwnedEnumerationPropertyTypes()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS:
        return ((InternalEList<?>)getOwnedPropertyValueGroups()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_TRACES:
        return ((InternalEList<?>)getOwnedTraces()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS:
        return ((InternalEList<?>)getOwnedPropertyValuePkgs()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS:
        return ((InternalEList<?>)getOwnedExchangeItems()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS:
        return ((InternalEList<?>)getOwnedAssociations()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES:
        return ((InternalEList<?>)getOwnedDataValues()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES:
        return ((InternalEList<?>)getOwnedMessageReferences()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS:
        return ((InternalEList<?>)getOwnedDataPkgs()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_CLASSES:
        return ((InternalEList<?>)getOwnedClasses()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS:
        return ((InternalEList<?>)getOwnedKeyParts()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS:
        return ((InternalEList<?>)getOwnedCollections()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_UNITS:
        return ((InternalEList<?>)getOwnedUnits()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES:
        return ((InternalEList<?>)getOwnedDataTypes()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_SIGNALS:
        return ((InternalEList<?>)getOwnedSignals()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGES:
        return ((InternalEList<?>)getOwnedMessages()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS:
        return ((InternalEList<?>)getOwnedExceptions()).basicRemove(otherEnd, msgs);
      case MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS:
        return ((InternalEList<?>)getOwnedStateEvents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslnewPackage.DATA_PKG__TYPE:
        return getType();
      case MyDslnewPackage.DATA_PKG__ID:
        return getId();
      case MyDslnewPackage.DATA_PKG__SID:
        return getSid();
      case MyDslnewPackage.DATA_PKG__NAME:
        return getName();
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_DOC:
        return getVisibleInDoc();
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_LM:
        return getVisibleInLM();
      case MyDslnewPackage.DATA_PKG__SUMMARY:
        return getSummary();
      case MyDslnewPackage.DATA_PKG__DESCRIPTION:
        return getDescription();
      case MyDslnewPackage.DATA_PKG__REVIEW:
        return getReview();
      case MyDslnewPackage.DATA_PKG__VISIBILITY:
        return getVisibility();
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUES:
        return getAppliedPropertyValues();
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUE_GROUPS:
        return getAppliedPropertyValueGroups();
      case MyDslnewPackage.DATA_PKG__STATUS:
        return getStatus();
      case MyDslnewPackage.DATA_PKG__FEATURES:
        return getFeatures();
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES:
        return getOwnedPropertyValues();
      case MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES:
        return getOwnedEnumerationPropertyTypes();
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS:
        return getOwnedPropertyValueGroups();
      case MyDslnewPackage.DATA_PKG__OWNED_TRACES:
        return getOwnedTraces();
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS:
        return getOwnedPropertyValuePkgs();
      case MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS:
        return getOwnedExchangeItems();
      case MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS:
        return getOwnedAssociations();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES:
        return getOwnedDataValues();
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES:
        return getOwnedMessageReferences();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS:
        return getOwnedDataPkgs();
      case MyDslnewPackage.DATA_PKG__OWNED_CLASSES:
        return getOwnedClasses();
      case MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS:
        return getOwnedKeyParts();
      case MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS:
        return getOwnedCollections();
      case MyDslnewPackage.DATA_PKG__OWNED_UNITS:
        return getOwnedUnits();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES:
        return getOwnedDataTypes();
      case MyDslnewPackage.DATA_PKG__OWNED_SIGNALS:
        return getOwnedSignals();
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGES:
        return getOwnedMessages();
      case MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS:
        return getOwnedExceptions();
      case MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS:
        return getOwnedStateEvents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslnewPackage.DATA_PKG__TYPE:
        setType((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__ID:
        setId((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__SID:
        setSid((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__NAME:
        setName((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_DOC:
        setVisibleInDoc((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_LM:
        setVisibleInLM((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__SUMMARY:
        setSummary((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__REVIEW:
        setReview((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBILITY:
        setVisibility((VisibilityKind)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUES:
        setAppliedPropertyValues((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUE_GROUPS:
        setAppliedPropertyValueGroups((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__STATUS:
        setStatus((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__FEATURES:
        setFeatures((String)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES:
        getOwnedPropertyValues().clear();
        getOwnedPropertyValues().addAll((java.util.Collection<? extends AbstractPropertyValue>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES:
        getOwnedEnumerationPropertyTypes().clear();
        getOwnedEnumerationPropertyTypes().addAll((java.util.Collection<? extends EnumerationPropertyType>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS:
        getOwnedPropertyValueGroups().clear();
        getOwnedPropertyValueGroups().addAll((java.util.Collection<? extends PropertyValueGroup>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_TRACES:
        getOwnedTraces().clear();
        getOwnedTraces().addAll((java.util.Collection<? extends Trace>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS:
        getOwnedPropertyValuePkgs().clear();
        getOwnedPropertyValuePkgs().addAll((java.util.Collection<? extends PropertyValuePkg>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS:
        getOwnedExchangeItems().clear();
        getOwnedExchangeItems().addAll((java.util.Collection<? extends ExchangeItem>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS:
        getOwnedAssociations().clear();
        getOwnedAssociations().addAll((java.util.Collection<? extends Association>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES:
        getOwnedDataValues().clear();
        getOwnedDataValues().addAll((java.util.Collection<? extends DataValue>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES:
        getOwnedMessageReferences().clear();
        getOwnedMessageReferences().addAll((java.util.Collection<? extends MessageReference>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS:
        getOwnedDataPkgs().clear();
        getOwnedDataPkgs().addAll((java.util.Collection<? extends DataPkg>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_CLASSES:
        getOwnedClasses().clear();
        getOwnedClasses().addAll((java.util.Collection<? extends org.xtext.example.newoamydsl.myDslnew.Class>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS:
        getOwnedKeyParts().clear();
        getOwnedKeyParts().addAll((java.util.Collection<? extends KeyPart>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS:
        getOwnedCollections().clear();
        getOwnedCollections().addAll((java.util.Collection<? extends Collection>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_UNITS:
        getOwnedUnits().clear();
        getOwnedUnits().addAll((java.util.Collection<? extends Unit>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES:
        getOwnedDataTypes().clear();
        getOwnedDataTypes().addAll((java.util.Collection<? extends DataType>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_SIGNALS:
        getOwnedSignals().clear();
        getOwnedSignals().addAll((java.util.Collection<? extends Signal>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGES:
        getOwnedMessages().clear();
        getOwnedMessages().addAll((java.util.Collection<? extends Message>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS:
        getOwnedExceptions().clear();
        getOwnedExceptions().addAll((java.util.Collection<? extends org.xtext.example.newoamydsl.myDslnew.Exception>)newValue);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS:
        getOwnedStateEvents().clear();
        getOwnedStateEvents().addAll((java.util.Collection<? extends StateEvent>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslnewPackage.DATA_PKG__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__ID:
        setId(ID_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__SID:
        setSid(SID_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_DOC:
        setVisibleInDoc(VISIBLE_IN_DOC_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_LM:
        setVisibleInLM(VISIBLE_IN_LM_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__SUMMARY:
        setSummary(SUMMARY_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__REVIEW:
        setReview(REVIEW_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__VISIBILITY:
        setVisibility(VISIBILITY_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUES:
        setAppliedPropertyValues(APPLIED_PROPERTY_VALUES_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUE_GROUPS:
        setAppliedPropertyValueGroups(APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__FEATURES:
        setFeatures(FEATURES_EDEFAULT);
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES:
        getOwnedPropertyValues().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES:
        getOwnedEnumerationPropertyTypes().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS:
        getOwnedPropertyValueGroups().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_TRACES:
        getOwnedTraces().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS:
        getOwnedPropertyValuePkgs().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS:
        getOwnedExchangeItems().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS:
        getOwnedAssociations().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES:
        getOwnedDataValues().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES:
        getOwnedMessageReferences().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS:
        getOwnedDataPkgs().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_CLASSES:
        getOwnedClasses().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS:
        getOwnedKeyParts().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS:
        getOwnedCollections().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_UNITS:
        getOwnedUnits().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES:
        getOwnedDataTypes().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_SIGNALS:
        getOwnedSignals().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGES:
        getOwnedMessages().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS:
        getOwnedExceptions().clear();
        return;
      case MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS:
        getOwnedStateEvents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslnewPackage.DATA_PKG__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case MyDslnewPackage.DATA_PKG__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case MyDslnewPackage.DATA_PKG__SID:
        return SID_EDEFAULT == null ? sid != null : !SID_EDEFAULT.equals(sid);
      case MyDslnewPackage.DATA_PKG__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_DOC:
        return VISIBLE_IN_DOC_EDEFAULT == null ? visibleInDoc != null : !VISIBLE_IN_DOC_EDEFAULT.equals(visibleInDoc);
      case MyDslnewPackage.DATA_PKG__VISIBLE_IN_LM:
        return VISIBLE_IN_LM_EDEFAULT == null ? visibleInLM != null : !VISIBLE_IN_LM_EDEFAULT.equals(visibleInLM);
      case MyDslnewPackage.DATA_PKG__SUMMARY:
        return SUMMARY_EDEFAULT == null ? summary != null : !SUMMARY_EDEFAULT.equals(summary);
      case MyDslnewPackage.DATA_PKG__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MyDslnewPackage.DATA_PKG__REVIEW:
        return REVIEW_EDEFAULT == null ? review != null : !REVIEW_EDEFAULT.equals(review);
      case MyDslnewPackage.DATA_PKG__VISIBILITY:
        return visibility != VISIBILITY_EDEFAULT;
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUES:
        return APPLIED_PROPERTY_VALUES_EDEFAULT == null ? appliedPropertyValues != null : !APPLIED_PROPERTY_VALUES_EDEFAULT.equals(appliedPropertyValues);
      case MyDslnewPackage.DATA_PKG__APPLIED_PROPERTY_VALUE_GROUPS:
        return APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT == null ? appliedPropertyValueGroups != null : !APPLIED_PROPERTY_VALUE_GROUPS_EDEFAULT.equals(appliedPropertyValueGroups);
      case MyDslnewPackage.DATA_PKG__STATUS:
        return STATUS_EDEFAULT == null ? status != null : !STATUS_EDEFAULT.equals(status);
      case MyDslnewPackage.DATA_PKG__FEATURES:
        return FEATURES_EDEFAULT == null ? features != null : !FEATURES_EDEFAULT.equals(features);
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUES:
        return ownedPropertyValues != null && !ownedPropertyValues.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_ENUMERATION_PROPERTY_TYPES:
        return ownedEnumerationPropertyTypes != null && !ownedEnumerationPropertyTypes.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_GROUPS:
        return ownedPropertyValueGroups != null && !ownedPropertyValueGroups.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_TRACES:
        return ownedTraces != null && !ownedTraces.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_PROPERTY_VALUE_PKGS:
        return ownedPropertyValuePkgs != null && !ownedPropertyValuePkgs.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_EXCHANGE_ITEMS:
        return ownedExchangeItems != null && !ownedExchangeItems.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_ASSOCIATIONS:
        return ownedAssociations != null && !ownedAssociations.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_VALUES:
        return ownedDataValues != null && !ownedDataValues.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGE_REFERENCES:
        return ownedMessageReferences != null && !ownedMessageReferences.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_PKGS:
        return ownedDataPkgs != null && !ownedDataPkgs.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_CLASSES:
        return ownedClasses != null && !ownedClasses.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_KEY_PARTS:
        return ownedKeyParts != null && !ownedKeyParts.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_COLLECTIONS:
        return ownedCollections != null && !ownedCollections.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_UNITS:
        return ownedUnits != null && !ownedUnits.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_DATA_TYPES:
        return ownedDataTypes != null && !ownedDataTypes.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_SIGNALS:
        return ownedSignals != null && !ownedSignals.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_MESSAGES:
        return ownedMessages != null && !ownedMessages.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_EXCEPTIONS:
        return ownedExceptions != null && !ownedExceptions.isEmpty();
      case MyDslnewPackage.DATA_PKG__OWNED_STATE_EVENTS:
        return ownedStateEvents != null && !ownedStateEvents.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", id: ");
    result.append(id);
    result.append(", sid: ");
    result.append(sid);
    result.append(", name: ");
    result.append(name);
    result.append(", visibleInDoc: ");
    result.append(visibleInDoc);
    result.append(", visibleInLM: ");
    result.append(visibleInLM);
    result.append(", summary: ");
    result.append(summary);
    result.append(", description: ");
    result.append(description);
    result.append(", review: ");
    result.append(review);
    result.append(", visibility: ");
    result.append(visibility);
    result.append(", appliedPropertyValues: ");
    result.append(appliedPropertyValues);
    result.append(", appliedPropertyValueGroups: ");
    result.append(appliedPropertyValueGroups);
    result.append(", status: ");
    result.append(status);
    result.append(", features: ");
    result.append(features);
    result.append(')');
    return result.toString();
  }

} //DataPkgImpl
