/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.eventBDSL.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.eventBDSL.ui.internal.EventBDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EventBDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EventBDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EventBDSLActivator activator = EventBDSLActivator.getInstance();
		return activator != null ? activator.getInjector(EventBDSLActivator.ORG_XTEXT_EXAMPLE_EVENTBDSL_EVENTBDSL) : null;
	}

}
