/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.newoamydsl.myDslnew;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concept</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getSid <em>Sid</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getVisibleInDoc <em>Visible In Doc</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getVisibleInLM <em>Visible In LM</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getSummary <em>Summary</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getAppliedPropertyValues <em>Applied Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getCompliances <em>Compliances</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getOwnedPropertyValues <em>Owned Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getOwnedEnumerationPropertyTypes <em>Owned Enumeration Property Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getOwnedPropertyValueGroups <em>Owned Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Concept#getCompositeLinks <em>Composite Links</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept()
 * @model
 * @generated
 */
public interface Concept extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Sid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sid</em>' attribute.
   * @see #setSid(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Sid()
   * @model
   * @generated
   */
  String getSid();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getSid <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sid</em>' attribute.
   * @see #getSid()
   * @generated
   */
  void setSid(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Visible In Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In Doc</em>' attribute.
   * @see #setVisibleInDoc(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_VisibleInDoc()
   * @model
   * @generated
   */
  String getVisibleInDoc();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getVisibleInDoc <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In Doc</em>' attribute.
   * @see #getVisibleInDoc()
   * @generated
   */
  void setVisibleInDoc(String value);

  /**
   * Returns the value of the '<em><b>Visible In LM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In LM</em>' attribute.
   * @see #setVisibleInLM(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_VisibleInLM()
   * @model
   * @generated
   */
  String getVisibleInLM();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getVisibleInLM <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In LM</em>' attribute.
   * @see #getVisibleInLM()
   * @generated
   */
  void setVisibleInLM(String value);

  /**
   * Returns the value of the '<em><b>Summary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Summary</em>' attribute.
   * @see #setSummary(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Summary()
   * @model
   * @generated
   */
  String getSummary();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getSummary <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Summary</em>' attribute.
   * @see #getSummary()
   * @generated
   */
  void setSummary(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Review</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Review</em>' attribute.
   * @see #setReview(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Review()
   * @model
   * @generated
   */
  String getReview();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getReview <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Review</em>' attribute.
   * @see #getReview()
   * @generated
   */
  void setReview(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Values</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Values</em>' attribute.
   * @see #setAppliedPropertyValues(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_AppliedPropertyValues()
   * @model
   * @generated
   */
  String getAppliedPropertyValues();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getAppliedPropertyValues <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Values</em>' attribute.
   * @see #getAppliedPropertyValues()
   * @generated
   */
  void setAppliedPropertyValues(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Value Groups</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #setAppliedPropertyValueGroups(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_AppliedPropertyValueGroups()
   * @model
   * @generated
   */
  String getAppliedPropertyValueGroups();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #getAppliedPropertyValueGroups()
   * @generated
   */
  void setAppliedPropertyValueGroups(String value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' attribute.
   * @see #setFeatures(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Features()
   * @model
   * @generated
   */
  String getFeatures();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getFeatures <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Features</em>' attribute.
   * @see #getFeatures()
   * @generated
   */
  void setFeatures(String value);

  /**
   * Returns the value of the '<em><b>Compliances</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compliances</em>' attribute.
   * @see #setCompliances(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_Compliances()
   * @model
   * @generated
   */
  String getCompliances();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Concept#getCompliances <em>Compliances</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compliances</em>' attribute.
   * @see #getCompliances()
   * @generated
   */
  void setCompliances(String value);

  /**
   * Returns the value of the '<em><b>Owned Property Values</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.AbstractPropertyValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Values</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_OwnedPropertyValues()
   * @model containment="true"
   * @generated
   */
  EList<AbstractPropertyValue> getOwnedPropertyValues();

  /**
   * Returns the value of the '<em><b>Owned Enumeration Property Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.EnumerationPropertyType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Enumeration Property Types</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_OwnedEnumerationPropertyTypes()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationPropertyType> getOwnedEnumerationPropertyTypes();

  /**
   * Returns the value of the '<em><b>Owned Property Value Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.PropertyValueGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Value Groups</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_OwnedPropertyValueGroups()
   * @model containment="true"
   * @generated
   */
  EList<PropertyValueGroup> getOwnedPropertyValueGroups();

  /**
   * Returns the value of the '<em><b>Composite Links</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.ItemInConcept}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composite Links</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getConcept_CompositeLinks()
   * @model containment="true"
   * @generated
   */
  EList<ItemInConcept> getCompositeLinks();

} // Concept
