/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.newoamydsl.myDslnew;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Operational Capability Involvement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getSid <em>Sid</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getVisibleInDoc <em>Visible In Doc</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getVisibleInLM <em>Visible In LM</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getSummary <em>Summary</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getRealizedFlow <em>Realized Flow</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getAppliedPropertyValues <em>Applied Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getInvolved <em>Involved</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getOwnedPropertyValues <em>Owned Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getOwnedEnumerationPropertyTypes <em>Owned Enumeration Property Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getOwnedPropertyValueGroups <em>Owned Property Value Groups</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement()
 * @model
 * @generated
 */
public interface EntityOperationalCapabilityInvolvement extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Sid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sid</em>' attribute.
   * @see #setSid(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Sid()
   * @model
   * @generated
   */
  String getSid();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getSid <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sid</em>' attribute.
   * @see #getSid()
   * @generated
   */
  void setSid(String value);

  /**
   * Returns the value of the '<em><b>Visible In Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In Doc</em>' attribute.
   * @see #setVisibleInDoc(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_VisibleInDoc()
   * @model
   * @generated
   */
  String getVisibleInDoc();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getVisibleInDoc <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In Doc</em>' attribute.
   * @see #getVisibleInDoc()
   * @generated
   */
  void setVisibleInDoc(String value);

  /**
   * Returns the value of the '<em><b>Visible In LM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In LM</em>' attribute.
   * @see #setVisibleInLM(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_VisibleInLM()
   * @model
   * @generated
   */
  String getVisibleInLM();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getVisibleInLM <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In LM</em>' attribute.
   * @see #getVisibleInLM()
   * @generated
   */
  void setVisibleInLM(String value);

  /**
   * Returns the value of the '<em><b>Summary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Summary</em>' attribute.
   * @see #setSummary(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Summary()
   * @model
   * @generated
   */
  String getSummary();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getSummary <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Summary</em>' attribute.
   * @see #getSummary()
   * @generated
   */
  void setSummary(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Review</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Review</em>' attribute.
   * @see #setReview(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Review()
   * @model
   * @generated
   */
  String getReview();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getReview <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Review</em>' attribute.
   * @see #getReview()
   * @generated
   */
  void setReview(String value);

  /**
   * Returns the value of the '<em><b>Realized Flow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realized Flow</em>' attribute.
   * @see #setRealizedFlow(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_RealizedFlow()
   * @model
   * @generated
   */
  String getRealizedFlow();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getRealizedFlow <em>Realized Flow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Realized Flow</em>' attribute.
   * @see #getRealizedFlow()
   * @generated
   */
  void setRealizedFlow(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Values</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Values</em>' attribute.
   * @see #setAppliedPropertyValues(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_AppliedPropertyValues()
   * @model
   * @generated
   */
  String getAppliedPropertyValues();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getAppliedPropertyValues <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Values</em>' attribute.
   * @see #getAppliedPropertyValues()
   * @generated
   */
  void setAppliedPropertyValues(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Value Groups</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #setAppliedPropertyValueGroups(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_AppliedPropertyValueGroups()
   * @model
   * @generated
   */
  String getAppliedPropertyValueGroups();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #getAppliedPropertyValueGroups()
   * @generated
   */
  void setAppliedPropertyValueGroups(String value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' attribute.
   * @see #setFeatures(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Features()
   * @model
   * @generated
   */
  String getFeatures();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getFeatures <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Features</em>' attribute.
   * @see #getFeatures()
   * @generated
   */
  void setFeatures(String value);

  /**
   * Returns the value of the '<em><b>Involved</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Involved</em>' attribute.
   * @see #setInvolved(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_Involved()
   * @model
   * @generated
   */
  String getInvolved();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.EntityOperationalCapabilityInvolvement#getInvolved <em>Involved</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Involved</em>' attribute.
   * @see #getInvolved()
   * @generated
   */
  void setInvolved(String value);

  /**
   * Returns the value of the '<em><b>Owned Property Values</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.AbstractPropertyValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Values</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_OwnedPropertyValues()
   * @model containment="true"
   * @generated
   */
  EList<AbstractPropertyValue> getOwnedPropertyValues();

  /**
   * Returns the value of the '<em><b>Owned Enumeration Property Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.EnumerationPropertyType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Enumeration Property Types</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_OwnedEnumerationPropertyTypes()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationPropertyType> getOwnedEnumerationPropertyTypes();

  /**
   * Returns the value of the '<em><b>Owned Property Value Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.PropertyValueGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Value Groups</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getEntityOperationalCapabilityInvolvement_OwnedPropertyValueGroups()
   * @model containment="true"
   * @generated
   */
  EList<PropertyValueGroup> getOwnedPropertyValueGroups();

} // EntityOperationalCapabilityInvolvement
