/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.newoamydsl.myDslnew;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getSid <em>Sid</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVisibleInDoc <em>Visible In Doc</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVisibleInLM <em>Visible In LM</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getSummary <em>Summary</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getRequirementId <em>Requirement Id</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAdditionalInformation <em>Additional Information</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVerificationMethod <em>Verification Method</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVerificationPhase <em>Verification Phase</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getImplementationVersion <em>Implementation Version</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getFeature <em>Feature</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAppliedPropertyValues <em>Applied Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getOwnedPropertyValues <em>Owned Property Values</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getOwnedEnumerationPropertyTypes <em>Owned Enumeration Property Types</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getOwnedPropertyValueGroups <em>Owned Property Value Groups</em>}</li>
 *   <li>{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getWnedTraces <em>Wned Traces</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement()
 * @model
 * @generated
 */
public interface Requirement extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Sid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sid</em>' attribute.
   * @see #setSid(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Sid()
   * @model
   * @generated
   */
  String getSid();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getSid <em>Sid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sid</em>' attribute.
   * @see #getSid()
   * @generated
   */
  void setSid(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Visible In Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In Doc</em>' attribute.
   * @see #setVisibleInDoc(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_VisibleInDoc()
   * @model
   * @generated
   */
  String getVisibleInDoc();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVisibleInDoc <em>Visible In Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In Doc</em>' attribute.
   * @see #getVisibleInDoc()
   * @generated
   */
  void setVisibleInDoc(String value);

  /**
   * Returns the value of the '<em><b>Visible In LM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible In LM</em>' attribute.
   * @see #setVisibleInLM(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_VisibleInLM()
   * @model
   * @generated
   */
  String getVisibleInLM();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVisibleInLM <em>Visible In LM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible In LM</em>' attribute.
   * @see #getVisibleInLM()
   * @generated
   */
  void setVisibleInLM(String value);

  /**
   * Returns the value of the '<em><b>Summary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Summary</em>' attribute.
   * @see #setSummary(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Summary()
   * @model
   * @generated
   */
  String getSummary();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getSummary <em>Summary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Summary</em>' attribute.
   * @see #getSummary()
   * @generated
   */
  void setSummary(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Review</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Review</em>' attribute.
   * @see #setReview(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Review()
   * @model
   * @generated
   */
  String getReview();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getReview <em>Review</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Review</em>' attribute.
   * @see #getReview()
   * @generated
   */
  void setReview(String value);

  /**
   * Returns the value of the '<em><b>Requirement Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement Id</em>' attribute.
   * @see #setRequirementId(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_RequirementId()
   * @model
   * @generated
   */
  String getRequirementId();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getRequirementId <em>Requirement Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement Id</em>' attribute.
   * @see #getRequirementId()
   * @generated
   */
  void setRequirementId(String value);

  /**
   * Returns the value of the '<em><b>Additional Information</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additional Information</em>' attribute.
   * @see #setAdditionalInformation(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_AdditionalInformation()
   * @model
   * @generated
   */
  String getAdditionalInformation();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAdditionalInformation <em>Additional Information</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additional Information</em>' attribute.
   * @see #getAdditionalInformation()
   * @generated
   */
  void setAdditionalInformation(String value);

  /**
   * Returns the value of the '<em><b>Verification Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verification Method</em>' attribute.
   * @see #setVerificationMethod(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_VerificationMethod()
   * @model
   * @generated
   */
  String getVerificationMethod();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVerificationMethod <em>Verification Method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verification Method</em>' attribute.
   * @see #getVerificationMethod()
   * @generated
   */
  void setVerificationMethod(String value);

  /**
   * Returns the value of the '<em><b>Verification Phase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verification Phase</em>' attribute.
   * @see #setVerificationPhase(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_VerificationPhase()
   * @model
   * @generated
   */
  String getVerificationPhase();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getVerificationPhase <em>Verification Phase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verification Phase</em>' attribute.
   * @see #getVerificationPhase()
   * @generated
   */
  void setVerificationPhase(String value);

  /**
   * Returns the value of the '<em><b>Implementation Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implementation Version</em>' attribute.
   * @see #setImplementationVersion(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_ImplementationVersion()
   * @model
   * @generated
   */
  String getImplementationVersion();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getImplementationVersion <em>Implementation Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implementation Version</em>' attribute.
   * @see #getImplementationVersion()
   * @generated
   */
  void setImplementationVersion(String value);

  /**
   * Returns the value of the '<em><b>Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' attribute.
   * @see #setFeature(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Feature()
   * @model
   * @generated
   */
  String getFeature();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getFeature <em>Feature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' attribute.
   * @see #getFeature()
   * @generated
   */
  void setFeature(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Values</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Values</em>' attribute.
   * @see #setAppliedPropertyValues(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_AppliedPropertyValues()
   * @model
   * @generated
   */
  String getAppliedPropertyValues();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAppliedPropertyValues <em>Applied Property Values</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Values</em>' attribute.
   * @see #getAppliedPropertyValues()
   * @generated
   */
  void setAppliedPropertyValues(String value);

  /**
   * Returns the value of the '<em><b>Applied Property Value Groups</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #setAppliedPropertyValueGroups(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_AppliedPropertyValueGroups()
   * @model
   * @generated
   */
  String getAppliedPropertyValueGroups();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getAppliedPropertyValueGroups <em>Applied Property Value Groups</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Applied Property Value Groups</em>' attribute.
   * @see #getAppliedPropertyValueGroups()
   * @generated
   */
  void setAppliedPropertyValueGroups(String value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' attribute.
   * @see #setFeatures(String)
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_Features()
   * @model
   * @generated
   */
  String getFeatures();

  /**
   * Sets the value of the '{@link org.xtext.example.newoamydsl.myDslnew.Requirement#getFeatures <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Features</em>' attribute.
   * @see #getFeatures()
   * @generated
   */
  void setFeatures(String value);

  /**
   * Returns the value of the '<em><b>Owned Property Values</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.AbstractPropertyValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Values</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_OwnedPropertyValues()
   * @model containment="true"
   * @generated
   */
  EList<AbstractPropertyValue> getOwnedPropertyValues();

  /**
   * Returns the value of the '<em><b>Owned Enumeration Property Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.EnumerationPropertyType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Enumeration Property Types</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_OwnedEnumerationPropertyTypes()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationPropertyType> getOwnedEnumerationPropertyTypes();

  /**
   * Returns the value of the '<em><b>Owned Property Value Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.PropertyValueGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Property Value Groups</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_OwnedPropertyValueGroups()
   * @model containment="true"
   * @generated
   */
  EList<PropertyValueGroup> getOwnedPropertyValueGroups();

  /**
   * Returns the value of the '<em><b>Wned Traces</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.newoamydsl.myDslnew.Trace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wned Traces</em>' containment reference list.
   * @see org.xtext.example.newoamydsl.myDslnew.MyDslnewPackage#getRequirement_WnedTraces()
   * @model containment="true"
   * @generated
   */
  EList<Trace> getWnedTraces();

} // Requirement
